services:

  storage:
    image: minio/minio
    command: minio server /data
    volumes:
      - storage_data:/data
    restart: always
    environment:
      MINIO_ACCESS_KEY: fakeaccesskey
      MINIO_SECRET_KEY: fakesecretkey
    ports:
      - "9000:9000"

  frontend:
    build: ../timeserver
    command: python3 server.py
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      S3_ENDPOINT:            http://storage:9000
      S3_USE_PATH_STYLE:      1
      S3_ACCESS_KEY_ID:       fakeaccesskey
      S3_SECRET_ACCESS_KEY:   fakesecretkey
    ports:
      - "8080:80"

volumes:
    db_data:
    storage_data:
