apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver
spec:
  replicas: 5
  selector:
    matchLabels:
      pod: timeserver-pod
  template:
    metadata:
      labels:
        pod: timeserver-pod
    spec:
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:4
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
            ephemeral-storage: 5Gi
          limits:
            cpu: 70m
            memory: 70Mi