apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: timeserver
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       timeserver
  updatePolicy:
    updateMode: "Off"

