apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: pi
  template:
    metadata:
      labels:
        pod: pi
    spec:
      containers:
      - name: pi-container
        image: docker.io/wdenniss/pi_worker:4
        env:
        - name: REDIS_HOST
          value: redis-0.redis-service
        - name: PYTHONUNBUFFERED
          value: "1"
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          exec:
            command: ["./check_liveness.sh", "logs/lastrun.date", "300"]
          successThreshold: 1
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 120
